env:
  global:
  - CC_TEST_REPORTER_ID=4e686c4a47ba63790e0af9db93ca51066ed8a856427599cfd58007190200ecdb

language: php

php:
- '7.1'
- '7.2'

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
- cp .env.example .env
- travis_retry composer self-update
- travis_retry composer install --prefer-source --no-interaction --no-suggest
- php artisan key:generate

script:
- vendor/bin/phpunit --coverage-clover clover.xml

after_script:
- ./cc-test-reporter after-build -t clover --debug --exit-code $TRAVIS_TEST_RESULT
